FROM ubuntu:21.04
ARG VERSION=3.9
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y python$(VERSION) python3-pip python$(VERSION)-dev
COPY hello.py /
CMD [ "python3", "hello.py" ]