version: "3.8"

services:
  centos:
    build: 
      context: .
      dockerfile: Dockerfile
    image: redis-server
    working_dir: /usr/src/bin
    command: /bin/sh -c "./redis-server ./redis.conf"  
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/src/bin/redis.conf
      - ./data:/usr/src/bin/data