version: "3.8"

services:
  centos:
    build: 
      context: .
      dockerfile: Dockerfile
    image: redis-server
    command: /bin/sh -c "while true; do sleep 3600; done;"
    ports:
      - 6379:6379
    volumes:
      - ./redis/:/usr/src/bin/bin/
      - ./data:/usr/src/bin/bin/data