version: "3.8"

services:
  centos:
    build: 
      context: .
      dockerfile: Dockerfile
    image: redis-server
    command: /usr/src/bin/bin/redis-server ./redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./redis:/usr/src/bin/bin/redis.conf:ro
      - ./data:/usr/src/bin/bin/data