version: "3.8"

services:
  centos:
    build: 
      context: .
      dockerfile: Dockerfile
    image: redis-server
    command: /bin/bash -c "cd /usr/src/bin && ./redis-server"
      
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/src/bin/redis.conf
      - ./data:/usr/src/bin/data