version: "3.8"

services:
  flask-demo:
    build: 
      context: ./flask
      dockerfile: Dockerfile.dev
    image: flask-demo
    environment:
      - REDIS_HOST=redis-server
    networks:
      - demo-network


  redis-server:
    image: redis:latest
    networks:
      - demo-network
      
  box1:
    image: box1
    command: /bin/sh -c "while true; do sleep 3600; done"
    networks:
      - demo-network
networks:
  demo-network: